name: Build C++ Project

on:
  push:
    branches: [ "main", "branch_mode" ]
  pull_request:
    branches: [ "main", "branch_mode" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ mingw-w64

    - name: Build Project
      run: |
        chmod +x automatations/auto_all_compile.sh
        ./automatations/auto_all_compile.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cpp-build-artifacts
        path: build/
